import type { Metadata } from "next";
import { Cinzel, Roboto} from "next/font/google";
import "./globals.css";
import React from "react";
import { Footer, Header } from "@/components";

const cinzel = Cinzel({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const subFont = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin']
})
export const metadata: Metadata = {
  title: "LAVAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.className} ${subFont.variable} antialiased`}
      >
        <Header/>
        <div>
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
